#!/usr/bin/env bash

if [ $# -eq 0 ]; then echo "$(basename "$0") <book title>" >&2; exit 1; fi
if ! command -v wget &>/dev/null; then echo "wget not installed" >&2; exit 2; fi
if ! command -v psql &>/dev/null; then echo "psql not installed" >&2; exit 2; fi
if ! command -v pandoc &>/dev/null; then echo "pandoc not installed" >&2; exit 2; fi

book_name="$1"
file_name="${book_name// /-}"
html_name="/tmp/${file_name,,}.html"
file_name="/tmp/${file_name,,}.md"
css_file="/tmp/github-markdown-dark.css"

if ! wget -q -c 'https://raw.githubusercontent.com/sindresorhus/github-markdown-css/refs/heads/main/github-markdown-dark.css' -O "${css_file}"
then
    echo "failed to download css file" >&2
    exit 1
fi

if ! psql -U flashback -At -c "select note from export_resource_by_name('$book_name') order by section_index, note_index;" > "${file_name}"
then
    echo "failed to export from database" >&2
    exit 1
fi

if pandoc "${file_name}" -o "${html_name}" --metadata title="${book_name}" --standalone --css "${css_file}"
then
    echo "exported to ${html_name}" >&2
else
    echo "failed to convert md to html" >&2
    exit 1
fi
