#!/usr/bin/env bash

while IFS="|" read -r id name type pattern link
do
    printf '\033[1;35m%3d\033[0m \033[1;34m%7s\033[0m with \033[1;34m%-8s\033[0m: \033[1;33m%s\033[0m %s\n' "${id}" "${type}" "${pattern}" "${name}" "$link"

    while read -rp "When did it release? " production </dev/tty
    do
        if is_numeric $production
        then
            psql -U flashback -c "update resources set production = '$production-01-01' where id = $id"
            break
        fi
    done

    while read -rp "When does it expire? " expiration </dev/tty
    do
        if is_numeric $expiration
        then
            psql -U flashback -c "update resources set expiration = '$expiration-01-01' where id = $id"
            break
        fi
    done
done < <(psql -U flashback -c "select id, name, type, pattern, link from resources where now() - production < '1 month'::interval order by name" -At)
