#!/usr/bin/env bash

pg_dump -d flashback -f flashback.sql
pg_dump -d flashback -f schema.sql --schema-only
sudo -u postgres psql -c 'drop database flashback_test'
sudo -u postgres psql -c 'create database flashback_test with owner flashback connection limit 3'
sudo -u postgres psql -d flashback_test -f schema.sql -q
