#!/usr/bin/env bash

pg_dump -U flashback -d flashback -f schema.sql --schema-only
psql -U postgres -c 'drop database flashback_test'
psql -U postgres -c 'create database flashback_test with owner flashback connection limit 3'
psql -U flashback -d flashback_test -f schema.sql -q
